import { contextBridge, ipcRenderer } from 'electron';
import type { InterviewOSApi } from '../shared/ipc';

// Keep preload self-contained. Sandboxed Electron preload scripts may only
// load a restricted set of modules, so runtime imports from application code
// are deliberately avoided here.
const IPC = {
  getState: 'workspace:get-state',
  resetDemo: 'workspace:reset-demo',
  saveProfile: 'profile:save',
  saveKnowledge: 'knowledge:save',
  deleteKnowledge: 'knowledge:delete',
  saveProject: 'project:save',
  analyzeJob: 'job:analyze',
  deleteJobAnalysis: 'job:delete-analysis',
  deleteJobAnalyses: 'job:delete-analyses',
  saveApplication: 'application:save',
  saveResumeVariant: 'resume-variant:save',
  saveJobSource: 'job-source:save',
  saveJobFilterPreset: 'job-filter:save',
  deleteJobFilterPreset: 'job-filter:delete',
  saveJobAlertRule: 'job-alert:save',
  deleteJobAlertRule: 'job-alert:delete',
  validateJobSource: 'job-source:validate',
  saveCareerSearchPlan: 'career-search-plan:save',
  runCareerSearchPlan: 'career-search-plan:run',
  saveCareerMemory: 'career-memory:save',
  saveCompanyWatch: 'company-watch:save',
  validateCompanyWatch: 'company-watch:validate',
  checkCompanyWatchesOnStartup: 'company-watch:startup-check',
  getJobSyncStatus: 'job-sync:status',
  promoteSyncedJob: 'job-sync:promote',
  updateSyncedJobStatus: 'job-sync:update-status',
  bulkUpdateSyncedJobStatus: 'job-sync:update-status-bulk',
  bulkRestoreSyncedJobs: 'job-sync:restore-bulk',
  deleteSyncedJobPermanently: 'job-sync:delete-permanently',
  bulkDeleteSyncedJobsPermanently: 'job-sync:delete-permanently-bulk',
  startTraining: 'training:start',
  submitTraining: 'training:submit',
  finalizeTraining: 'training:finalize',
  coachTraining: 'training:coach',
  createBackup: 'backup:create',
  clearWorkspaceData: 'workspace:clear-data',
  exportMarkdown: 'export:markdown',
  exportJobData: 'export:job-data',
  saveProvider: 'provider:save',
  testProvider: 'provider:test',
  getMeta: 'app:get-meta',
  copyText: 'clipboard:write-text',
  importDocument: 'document:import',
  selectObsidianVault: 'obsidian:select-vault',
  createObsidianVault: 'obsidian:create-vault',
  testObsidianVault: 'obsidian:test-vault',
  getObsidianSettings: 'obsidian:get-settings',
  updateObsidianSettings: 'obsidian:update-settings',
  previewObsidianSync: 'obsidian:preview-initial-sync',
  runObsidianSync: 'obsidian:run-sync',
  getObsidianStatus: 'obsidian:get-status',
  openObsidianNote: 'obsidian:open-note',
  openObsidianFolder: 'obsidian:open-folder',
  copyObsidianWikiLink: 'obsidian:copy-wikilink',
  disconnectObsidian: 'obsidian:disconnect'
} as const;

const api: InterviewOSApi = {
  getState: () => ipcRenderer.invoke(IPC.getState),
  resetDemo: () => ipcRenderer.invoke(IPC.resetDemo),
  saveProfile: (input) => ipcRenderer.invoke(IPC.saveProfile, input),
  saveKnowledge: (input) => ipcRenderer.invoke(IPC.saveKnowledge, input),
  deleteKnowledge: (id) => ipcRenderer.invoke(IPC.deleteKnowledge, id),
  saveProject: (input) => ipcRenderer.invoke(IPC.saveProject, input),
  analyzeJob: (input) => ipcRenderer.invoke(IPC.analyzeJob, input),
  deleteJobAnalysis: (id) => ipcRenderer.invoke(IPC.deleteJobAnalysis, id),
  deleteJobAnalyses: (ids) => ipcRenderer.invoke(IPC.deleteJobAnalyses, ids),
  saveApplication: (input) => ipcRenderer.invoke(IPC.saveApplication, input),
  saveResumeVariant: (input) => ipcRenderer.invoke(IPC.saveResumeVariant, input),
  saveJobSource: (input) => ipcRenderer.invoke(IPC.saveJobSource, input),
  saveJobFilterPreset: (input) => ipcRenderer.invoke(IPC.saveJobFilterPreset, input),
  deleteJobFilterPreset: (id) => ipcRenderer.invoke(IPC.deleteJobFilterPreset, id),
  saveJobAlertRule: (input) => ipcRenderer.invoke(IPC.saveJobAlertRule, input),
  deleteJobAlertRule: (id) => ipcRenderer.invoke(IPC.deleteJobAlertRule, id),
  validateJobSource: (id) => ipcRenderer.invoke(IPC.validateJobSource, id),
  saveCareerSearchPlan: (input) => ipcRenderer.invoke(IPC.saveCareerSearchPlan, input),
  runCareerSearchPlan: (id) => ipcRenderer.invoke(IPC.runCareerSearchPlan, id),
  saveCareerMemory: (input) => ipcRenderer.invoke(IPC.saveCareerMemory, input),
  saveCompanyWatch: (input) => ipcRenderer.invoke(IPC.saveCompanyWatch, input),
  validateCompanyWatch: (id) => ipcRenderer.invoke(IPC.validateCompanyWatch, id),
  checkCompanyWatchesOnStartup: () => ipcRenderer.invoke(IPC.checkCompanyWatchesOnStartup),
  getJobSyncStatus: () => ipcRenderer.invoke(IPC.getJobSyncStatus),
  promoteSyncedJob: (id) => ipcRenderer.invoke(IPC.promoteSyncedJob, id),
  updateSyncedJobStatus: (id, status) => ipcRenderer.invoke(IPC.updateSyncedJobStatus, id, status),
  bulkUpdateSyncedJobStatus: (ids, status) => ipcRenderer.invoke(IPC.bulkUpdateSyncedJobStatus, ids, status),
  bulkRestoreSyncedJobs: (ids) => ipcRenderer.invoke(IPC.bulkRestoreSyncedJobs, ids),
  deleteSyncedJobPermanently: (id) => ipcRenderer.invoke(IPC.deleteSyncedJobPermanently, id),
  bulkDeleteSyncedJobsPermanently: (ids) => ipcRenderer.invoke(IPC.bulkDeleteSyncedJobsPermanently, ids),
  startTraining: (input) => ipcRenderer.invoke(IPC.startTraining, input),
  submitTraining: (input) => ipcRenderer.invoke(IPC.submitTraining, input),
  finalizeTraining: (input) => ipcRenderer.invoke(IPC.finalizeTraining, input),
  coachTraining: (input) => ipcRenderer.invoke(IPC.coachTraining, input),
  createBackup: () => ipcRenderer.invoke(IPC.createBackup),
  clearWorkspaceData: () => ipcRenderer.invoke(IPC.clearWorkspaceData),
  exportMarkdown: () => ipcRenderer.invoke(IPC.exportMarkdown),
  exportJobData: (kind) => ipcRenderer.invoke(IPC.exportJobData, kind),
  saveProvider: (input) => ipcRenderer.invoke(IPC.saveProvider, input),
  testProvider: () => ipcRenderer.invoke(IPC.testProvider),
  getMeta: () => ipcRenderer.invoke(IPC.getMeta),
  copyText: (value) => ipcRenderer.invoke(IPC.copyText, value),
  importDocument: (target) => ipcRenderer.invoke(IPC.importDocument, target),
  selectObsidianVault: () => ipcRenderer.invoke(IPC.selectObsidianVault),
  createObsidianVault: () => ipcRenderer.invoke(IPC.createObsidianVault),
  testObsidianVault: () => ipcRenderer.invoke(IPC.testObsidianVault),
  getObsidianSettings: () => ipcRenderer.invoke(IPC.getObsidianSettings),
  updateObsidianSettings: (input) => ipcRenderer.invoke(IPC.updateObsidianSettings, input),
  previewObsidianSync: (input) => ipcRenderer.invoke(IPC.previewObsidianSync, input),
  runObsidianSync: (input) => ipcRenderer.invoke(IPC.runObsidianSync, input),
  getObsidianStatus: () => ipcRenderer.invoke(IPC.getObsidianStatus),
  openObsidianNote: (entityId) => ipcRenderer.invoke(IPC.openObsidianNote, entityId),
  openObsidianFolder: () => ipcRenderer.invoke(IPC.openObsidianFolder),
  copyObsidianWikiLink: (entityId) => ipcRenderer.invoke(IPC.copyObsidianWikiLink, entityId),
  disconnectObsidian: () => ipcRenderer.invoke(IPC.disconnectObsidian)
};

contextBridge.exposeInMainWorld('interviewOS', api);
